//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_VanLangHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coc_Phong
    {
        public string Ma_Coc_Phong { get; set; }
        public string Ma_Tour { get; set; }
        public string Ma_TT_Dat_Phong { get; set; }
        public string Ma_Phong { get; set; }
        public System.DateTime Ngay_Bat_Dau { get; set; }
        public System.DateTime Ngay_Ket_Thuc { get; set; }
        public int Trang_Thai { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual TOUR TOUR { get; set; }
        public virtual TT_Dat_Phong TT_Dat_Phong { get; set; }
    }
}
