//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_VanLangHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_Tien_Ich
    {
        public string Ma_DS_Tien_Ich { get; set; }
        public string Ma_Loai_Phong { get; set; }
        public string Ma_Tien_Ich { get; set; }
    
        public virtual Loai_Phong Loai_Phong { get; set; }
        public virtual Tien_Ich Tien_Ich { get; set; }
    }
}
