//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_VanLangHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loai_Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loai_Phong()
        {
            this.DS_Tien_Ich = new HashSet<DS_Tien_Ich>();
            this.Phong = new HashSet<Phong>();
        }
    
        public string Ma_Loai_Phong { get; set; }
        public string Ten_Loai_Phong { get; set; }
        public int So_Nguoi_Lon { get; set; }
        public int So_Tre_Em { get; set; }
        public int So_Em_Be { get; set; }
        public int So_Giuong { get; set; }
        public decimal Gia { get; set; }
        public string Mo_Ta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DS_Tien_Ich> DS_Tien_Ich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong> Phong { get; set; }
    }
}
