//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_VanLangHotel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEP25Team09Entities : DbContext
    {
        public SEP25Team09Entities()
            : base("name=SEP25Team09Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DS_Tien_Ich> DS_Tien_Ich { get; set; }
        public virtual DbSet<Khach_San> Khach_San { get; set; }
        public virtual DbSet<Loai_Phong> Loai_Phong { get; set; }
        public virtual DbSet<Phong> Phong { get; set; }
        public virtual DbSet<Quyen> Quyen { get; set; }
        public virtual DbSet<Tai_Khoan> Tai_Khoan { get; set; }
        public virtual DbSet<Tien_Ich> Tien_Ich { get; set; }
        public virtual DbSet<TT_Dat_Phong> TT_Dat_Phong { get; set; }
        public virtual DbSet<TT_Doi_Phong> TT_Doi_Phong { get; set; }
        public virtual DbSet<Trang_Thai> Trang_Thai { get; set; }
    }
}
