//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_VanLangHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhan_Than
    {
        public string Ma_Nhan_Than { get; set; }
        public string Ho_Ten { get; set; }
        public string CMND_CCCD { get; set; }
        public System.DateTime Sinh_Nhat { get; set; }
        public int Gioi_Tinh { get; set; }
        public string Gioi_Tinh_Name { get; set; }
        public string Dia_Chi { get; set; }
        public string Moi_Quan_He { get; set; }
        public string Ma_TT_Dat_Phong { get; set; }
    
        public virtual TT_Dat_Phong TT_Dat_Phong { get; set; }
    }
}
