//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_VanLangHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sao_Ke
    {
        public string Ma_Sao_Ke { get; set; }
        public string Ma_TT_Dat_Phong { get; set; }
        public string Ma_Tour { get; set; }
        public string Ma_Tai_Khoan { get; set; }
        public decimal So_Tien { get; set; }
        public System.DateTime Ngay_Giao_Dich { get; set; }
        public Nullable<int> Coc_or_ThanhToan { get; set; }
        public string Note { get; set; }
    
        public virtual Tai_Khoan Tai_Khoan { get; set; }
        public virtual TOUR TOUR { get; set; }
        public virtual TT_Dat_Phong TT_Dat_Phong { get; set; }
    }
}
