//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_VanLangHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tien_Ich
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tien_Ich()
        {
            this.DS_Tien_Ich = new HashSet<DS_Tien_Ich>();
        }
    
        public string Ma_Tien_Ich { get; set; }
        public string Ten_Tien_Ich { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DS_Tien_Ich> DS_Tien_Ich { get; set; }

        public bool IsChecks { get; set; }
    }

    public class ListTienIch {
        public List<Tien_Ich> tienIch { get; set; }
    }
} 
