//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_VanLangHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        public string Ma_Tour { get; set; }
        public string Ho_Ten_Chu_Tour { get; set; }
        public string CMND_CCCD { get; set; }
        public string SDT { get; set; }
        public System.DateTime Sinh_Nhat { get; set; }
        public int Gioi_Tinh { get; set; }
        public string Email { get; set; }
        public string Dia_Chi { get; set; }
        public System.DateTime Thoi_Gian_DatPhong_Coc { get; set; }
        public System.DateTime Thoi_Gian_NhanPhong { get; set; }
        public System.DateTime Thoi_Gian_TraPhong { get; set; }
        public Nullable<System.DateTime> Thoi_Gian_ThanhToan_Huy { get; set; }
        public decimal So_Tien_Coc { get; set; }
        public decimal Tong_Thanh_Toan { get; set; }
        public int Trang_Thai { get; set; }
        public string Ma_Tai_Khoan { get; set; }
    
        public virtual Tai_Khoan Tai_Khoan { get; set; }
    }
}
