//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_VanLangHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_Doi_Phong
    {
        public string Ma_TT_Doi_Phong { get; set; }
        public int Lan_Doi { get; set; }
        public int Doi_Tra { get; set; }
        public System.DateTime TG_Nhan_Phong { get; set; }
        public System.DateTime TG_Doi_Tra { get; set; }
        public string Ma_TT_Dat_Phong { get; set; }
        public string Ma_Phong { get; set; }
        public string Ma_Tai_Khoan { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual Tai_Khoan Tai_Khoan { get; set; }
        public virtual TT_Dat_Phong TT_Dat_Phong { get; set; }
    }
}
