//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_VanLangHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_Dat_Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TT_Dat_Phong()
        {
            this.Nhan_Than = new HashSet<Nhan_Than>();
            this.Sao_Ke = new HashSet<Sao_Ke>();
            this.TT_Doi_Phong = new HashSet<TT_Doi_Phong>();
            this.Coc_Phong = new HashSet<Coc_Phong>();
        }
    
        public string Ma_TT_Dat_Phong { get; set; }
        public string Ho_Ten_KH { get; set; }
        public string CMND_CCCD_KH { get; set; }
        public string SDT_KH { get; set; }
        public System.DateTime Sinh_Nhat_KH { get; set; }
        public int Gioi_Tinh_KH { get; set; }
        public string Dia_Chi_KH { get; set; }
        public int Doi_Tra { get; set; }
        public System.DateTime Thoi_Gian_Dat { get; set; }
        public System.DateTime Thoi_Gian_Doi_Tra { get; set; }
        public string Ma_Phong { get; set; }
        public string Ma_Tai_Khoan { get; set; }
        public string Ma_Tour { get; set; }
        public int Nguoi_Lon { get; set; }
        public int Tre_Em { get; set; }
        public decimal Tong_Thanh_Toan { get; set; }
        public decimal Tien_Coc { get; set; }
        public int Trang_Thai { get; set; }
        public string TaiKhoanThanhToanOrHuy { get; set; }
        public Nullable<System.DateTime> Thoi_Gian_ThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nhan_Than> Nhan_Than { get; set; }
        public virtual Phong Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sao_Ke> Sao_Ke { get; set; }
        public virtual Tai_Khoan Tai_Khoan { get; set; }
        public virtual Tai_Khoan Tai_Khoan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_Doi_Phong> TT_Doi_Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coc_Phong> Coc_Phong { get; set; }
    }
}
